### ISSUE TITLE
got this error

### ISSUE THREAD

**Issue by aleisteramich** [DarkFirePhoenixX/Google-Drive-PDF-Document-Downloader-Script#1]
VM640 jspdf.debug.js:1922  Uncaught RangeError: Invalid string length
    at Array.join (<anonymous>)
    at API.__private__.buildDocument (VM640 jspdf.debug.js:1922:24)
    at API.save (VM640 jspdf.debug.js:3648:26)
    at generatePDF (<anonymous>:47:12)
    at <anonymous>:88:25

**Comment by DarkFirePhoenixX** [comment]
Tested the script in different browsers. Seems to work just fine. Where have you tested the script and when did the error pop up?

**Comment by DarkFirePhoenixX** [comment]
> VM640 jspdf.debug.js:1922 Uncaught RangeError: Invalid string length at Array.join () at API.**private**.buildDocument (VM640 jspdf.debug.js:1922:24) at API.save (VM640 jspdf.debug.js:3648:26) at generatePDF (:47:12) at :88:25

Tested the script in different browsers. Seems to work just fine. Where have you tested the script and when did the error pop up?
